### PR TITLE
Support SDWebImage 4.0

### PR DESCRIPTION
**Pull request by dvlprliu**

### CODE REVIEW

**Comment by ide** [comment]
Can you please write a few sentences explaining how you tested this?

**Comment by dvlprliu** [comment]
I will create a demo repo about this PR.

**Comment by dvlprliu** [comment]
Hi @ide , sorry for the wait, I've been busy on my job.   
I created a [repo](https://github.com/dvlprliu/WebASDKImageDemo) about this PR to test things out.  What I did is pretty simple, create a ASNetworkingImageNode with default or custom setting as README says, give it a url the image shows, and then I check the cache to see whether if the image is in the cache. It works pretty well.   
  ;)

**Comment by ide** [comment]
Thanks for this PR and for the test repo!

**Pull request merged**
